services:
  db:
    image: postgres:16
    container_name: incident_db
    environment:
      POSTGRES_USER: incident_user
      POSTGRES_PASSWORD: incident_pass
      POSTGRES_DB: incident_db
    ports:
      - "5432:5432"
    volumes:
      - incident_pgdata:/var/lib/postgresql/data

volumes:
  incident_pgdata:
